#!/bin/sh
# Format staged nix files before commit and re-stage them

# Exit if there are no staged files
stagedFiles=$(git diff --cached --name-only --diff-filter=ACM | grep '\.nix$')
if [ -z "$stagedFiles" ]; then
	exit 0
fi

# Format staged files
nix fmt $stagedFiles
# Re-stage files
git add $stagedFiles

# Exit if there are no changes
if git diff --cached --exit-code >/dev/null; then
	echo "No changes after formatting"
	exit 1
fi

exit 0
