return {

--   -- notify customization
--   {
--     "rcarriga/nvim-notify",
--     opts = {
--       stages = "fade_in_slide_out",
--       timeout = 3000,
--       render = "compact",
--     },
--     -- enabled = false,
--   },
--
--   -- bufferline
--   {
--     "akinsho/bufferline.nvim",
--     opts = {
--       options = {
--         numbers = "none", -- | "ordinal" | "buffer_id" | "both" | function({ ordinal, id, lower, raise }): string,
--         close_command = "bdelete! %d", -- can be a string | function, see "Mouse actions"
--         right_mouse_command = "bdelete! %d", -- can be a string | function, see "Mouse actions"
--         max_name_length = 30,
--         max_prefix_length = 30, -- prefix used when a buffer is de-duplicated
--         show_buffer_icons = true,
--         show_buffer_close_icons = true,
--         show_close_icon = false,
--         show_tab_indicators = true,
--         separator_style = "thin", -- | "thick" | "thin" | { 'any', 'any' },
--         color_icons = true,
--         diagnostics = false,
--         highlights = {
--           buffer_selected = {
--             gui = "none",
--           },
--         },
--         offsets = {
--           {
--             filetype = "neo-tree",
--             text = "Neo-tree",
--             highlight = "Directory",
--             text_align = "left",
--           },
--           {
--             filetype = "Outline",
--             text = "Symbols Outline",
--             highlight = "TSType",
--             text_align = "left",
--           },
--         },
--       },
--     },
--   },
--
--   -- statusline
--   {
--     "nvim-lualine/lualine.nvim",
--     event = "VeryLazy",
--     opts = function(_, opts)
--       local function lsp_name(msg)
--         msg = msg or "Inactive"
--         local buf_clients = vim.lsp.get_active_clients()
--         if next(buf_clients) == nil then
--           if type(msg) == "boolean" or #msg == 0 then
--             return "Inactive"
--           end
--           return msg
--         end
--         local buf_client_names = {}
--
--         for _, client in pairs(buf_clients) do
--           if client.name ~= "null-ls" then
--             table.insert(buf_client_names, client.name)
--           end
--         end
--
--         return table.concat(buf_client_names, ", ")
--       end
--
--       opts.sections = vim.tbl_deep_extend("force", opts.sections, {
--         lualine_y = {
--           {
--             lsp_name,
--             icon = "",
--             color = { gui = "none" },
--           },
--           { "progress", separator = " ", padding = { left = 1, right = 0 } },
--           { "location", padding = { left = 0, right = 1 } },
--         },
--       })
--     end,
--   },
--
--   -- scrollbar for Neovim
--   {
--     "dstein64/nvim-scrollview",
--     event = "BufReadPre",
--     opts = {
--       excluded_filetypes = { "alpha", "neo-tree" },
--       current_only = true,
--       winblend = 75,
--     },
--   },
}
